import { Battlefield } from '../types/aliases'

export enum BATTLEFIELD_LINE {
    ENEMY_SIEGE = 'ENEMY_SIEGE',
    ENEMY_RANGED = 'ENEMY_RANGED',
    ENEMY_MELEE = 'ENEMY_MELEE',
    PLAYER_MELEE = 'PLAYER_MELEE',
    PLAYER_RANGED = 'PLAYER_RANGED',
    PLAYER_SIEGE = 'PLAYER_SIEGE',
}

export const PLAYER_LINES = [
    BATTLEFIELD_LINE.PLAYER_MELEE,
    BATTLEFIELD_LINE.PLAYER_RANGED,
    BATTLEFIELD_LINE.PLAYER_SIEGE,
]

export const ENEMY_LINES = [
    BATTLEFIELD_LINE.ENEMY_MELEE,
    BATTLEFIELD_LINE.ENEMY_RANGED,
    BATTLEFIELD_LINE.ENEMY_SIEGE,
]

export const LINES_NAME: Record<BATTLEFIELD_LINE, string> = {
    [BATTLEFIELD_LINE.ENEMY_SIEGE]: 'Siege',
    [BATTLEFIELD_LINE.ENEMY_RANGED]: 'Ranged',
    [BATTLEFIELD_LINE.ENEMY_MELEE]: 'Melee',
    [BATTLEFIELD_LINE.PLAYER_MELEE]: 'Melee',
    [BATTLEFIELD_LINE.PLAYER_RANGED]: 'Ranged',
    [BATTLEFIELD_LINE.PLAYER_SIEGE]: 'Siege',
}

export const EMPTY_BATTLEFIELD_ROWS: Battlefield = {
    [BATTLEFIELD_LINE.ENEMY_SIEGE]: [],
    [BATTLEFIELD_LINE.ENEMY_RANGED]: [],
    [BATTLEFIELD_LINE.ENEMY_MELEE]: [],
    [BATTLEFIELD_LINE.PLAYER_MELEE]: [],
    [BATTLEFIELD_LINE.PLAYER_RANGED]: [],
    [BATTLEFIELD_LINE.PLAYER_SIEGE]: [],
}

export enum DECK_TYPE {
    NORTHERN_REALMS = 'NORTHERN_REALMS',
    NILFGAARDIAN_EMPIRE = 'NILFGAARDIAN_EMPIRE',
    SCOIATAEL = 'SCOIATAEL',
    MONSTER = 'MONSTER',
    NEUTRAL = 'NEUTRAL',
}

export enum CARD_TYPE {
    PLACED = 'PLACED',
    EFFECT = 'EFFECT',
    MODIFIER = 'MODIFIER',
}

export enum PLACED_CARD_TYPE {
    MELEE = 'MELEE',
    RANGED = 'RANGED',
    SIEGE = 'SIEGE',
}

export const CARD_TYPE_NAMES: Record<CARD_TYPE, string> = {
    [CARD_TYPE.PLACED]: 'Unit',
    [CARD_TYPE.EFFECT]: 'Effect',
    [CARD_TYPE.MODIFIER]: 'Modifier',
}

export const PLACED_CARD_TYPE_NAMES: Record<PLACED_CARD_TYPE, string> = {
    [PLACED_CARD_TYPE.MELEE]: 'Melee',
    [PLACED_CARD_TYPE.RANGED]: 'Ranged',
    [PLACED_CARD_TYPE.SIEGE]: 'Siege',
}

export const CARD_AUTHORIZED_LINES: Record<PLACED_CARD_TYPE, BATTLEFIELD_LINE[]> = {
    [PLACED_CARD_TYPE.MELEE]: [BATTLEFIELD_LINE.ENEMY_MELEE, BATTLEFIELD_LINE.PLAYER_MELEE],
    [PLACED_CARD_TYPE.RANGED]: [BATTLEFIELD_LINE.ENEMY_RANGED, BATTLEFIELD_LINE.PLAYER_RANGED],
    [PLACED_CARD_TYPE.SIEGE]: [BATTLEFIELD_LINE.ENEMY_SIEGE, BATTLEFIELD_LINE.PLAYER_SIEGE],
}
