import { BattlefieldRows } from '../types/aliases'

export enum BATTLEFIELD_LINE {
    ENEMY_SIEGE,
    ENEMY_RANGED,
    ENEMY_MELEE,
    PLAYER_MELEE,
    PLAYER_RANGED,
    PLAYER_SIEGE,
}

export const PLAYER_LINES = [
    BATTLEFIELD_LINE.PLAYER_MELEE,
    BATTLEFIELD_LINE.PLAYER_RANGED,
    BATTLEFIELD_LINE.PLAYER_SIEGE,
]

export const ENEMY_LINES = [
    BATTLEFIELD_LINE.ENEMY_MELEE,
    BATTLEFIELD_LINE.ENEMY_RANGED,
    BATTLEFIELD_LINE.ENEMY_SIEGE,
]

export const LINES_NAME: Record<BATTLEFIELD_LINE, string> = {
    [BATTLEFIELD_LINE.ENEMY_SIEGE]: 'Siege',
    [BATTLEFIELD_LINE.ENEMY_RANGED]: 'Ranged',
    [BATTLEFIELD_LINE.ENEMY_MELEE]: 'Melee',
    [BATTLEFIELD_LINE.PLAYER_MELEE]: 'Melee',
    [BATTLEFIELD_LINE.PLAYER_RANGED]: 'Ranged',
    [BATTLEFIELD_LINE.PLAYER_SIEGE]: 'Siege',
}

export const EMPTY_BATTLEFIELD_ROWS: BattlefieldRows = {
    [BATTLEFIELD_LINE.ENEMY_SIEGE]: [],
    [BATTLEFIELD_LINE.ENEMY_RANGED]: [],
    [BATTLEFIELD_LINE.ENEMY_MELEE]: [],
    [BATTLEFIELD_LINE.PLAYER_MELEE]: [],
    [BATTLEFIELD_LINE.PLAYER_RANGED]: [],
    [BATTLEFIELD_LINE.PLAYER_SIEGE]: [],
}

export enum DECK_TYPE {
    NORTHERN_REALMS,
    NILFGAARDIAN_EMPIRE,
    SCOIATAEL,
    MONSTER,
    NEUTRAL,
}

export enum CARD_TYPE {
    PLACED,
    EFFECT,
    MODIFIER,
}

export enum PLACED_CARD_TYPE {
    MELEE,
    RANGED,
    SIEGE,
    HERO,
}

export const CARD_TYPE_NAMES: Record<CARD_TYPE, string> = {
    [CARD_TYPE.PLACED]: 'Unit',
    [CARD_TYPE.EFFECT]: 'Effect',
    [CARD_TYPE.MODIFIER]: 'Modifier',
}

export const PLACED_CARD_TYPE_NAMES: Record<PLACED_CARD_TYPE, string> = {
    [PLACED_CARD_TYPE.MELEE]: 'Melee',
    [PLACED_CARD_TYPE.RANGED]: 'Ranged',
    [PLACED_CARD_TYPE.SIEGE]: 'Siege',
    [PLACED_CARD_TYPE.HERO]: 'Hero',
}

export const CARD_AUTHORIZED_LINES: Record<PLACED_CARD_TYPE, BATTLEFIELD_LINE[]> = {
    [PLACED_CARD_TYPE.MELEE]: [BATTLEFIELD_LINE.ENEMY_MELEE, BATTLEFIELD_LINE.PLAYER_MELEE],
    [PLACED_CARD_TYPE.RANGED]: [BATTLEFIELD_LINE.ENEMY_RANGED, BATTLEFIELD_LINE.PLAYER_RANGED],
    [PLACED_CARD_TYPE.SIEGE]: [BATTLEFIELD_LINE.ENEMY_SIEGE, BATTLEFIELD_LINE.PLAYER_SIEGE],
    [PLACED_CARD_TYPE.HERO]: [],
}
